### ISSUE TITLE
Какие из этих файлов не нужны для комиляции проекта в MVS? 

### ISSUE THREAD

**Issue by st054745** [st054745/104GroupProject#3]
https://msdn.microsoft.com/ru-ru/library/hx0cxhaw.aspx

**Comment by st054745** [comment]
https://msdn.microsoft.com/ru-ru/library/hx0cxhaw.aspx

**Comment by 77maxikov** [comment]
.sdf, .suo, .user, readme.txt  - однозначно не нужны
